### ISSUE TITLE
Trying to decrease VM size and running into some issues

### ISSUE THREAD

**Issue by StanleyShen** [cloudfoundry/cf-release#933]
Hello, all

I am trying to create a new deployment file for minimizing VM size, and I started the work based on https://github.com/cloudfoundry-community/cf-boshworkspace

It looks it's not maintained right now, my question got no response for several days.
Anyway, I create an deployment file based on it, and when deploying I always got error about consul component.

The deployment file starts from https://github.com/cloudfoundry/cf-release/tree/master/example_manifests and adds diego components.
And did changes based on https://github.com/cloudfoundry-community/cf-boshworkspace to change default jobs.
```
  Started updating job backbone_z1 > backbone_z1/0 (canary)
  Started updating job data > data/0 (canary)
  Started updating job services_z1 > services_z1/0 (canary)
  Started updating job health_z1 > health_z1/0 (canary)
  Started updating job cell_z1 > cell_z1/0 (canary)
  Started updating job ha_proxy_z1 > ha_proxy_z1/0 (canary)
  Started updating job api_z1 > api_z1/0 (canary)
  Started updating job brain_z1 > brain_z1/0 (canary)
     Done updating job backbone_z1 > backbone_z1/0 (canary) (00:02:24)
     Done updating job brain_z1 > brain_z1/0 (canary) (00:03:25)
   Failed updating job ha_proxy_z1 > ha_proxy_z1/0 (canary): `ha_proxy_z1/0' is not running after update (00:10:28)
   Failed updating job data > data/0 (canary): `data/0' is not running after update (00:10:39)
   Failed updating job cell_z1 > cell_z1/0 (canary): `cell_z1/0' is not running after update (00:10:55)
   Failed updating job health_z1 > health_z1/0 (canary): `health_z1/0' is not running after update (00:11:25)
   Failed updating job services_z1 > services_z1/0 (canary): `services_z1/0' is not running after update (00:11:27)
   Failed updating job api_z1 > api_z1/0 (canary): `api_z1/0' is not running after update (00:14:08)

Error 400007: `ha_proxy_z1/0' is not running after update
```
And after checking the log of ha_proxy_z1 job, I can see the main problem is the consul.
Finally Itt complains
```
==> Error starting agent: Failed to start Consul client: Failed to start lan serf: Failed to start TCP listener. Err: listen tcp 10.0.0.25:8301: bind: address already in use
```

The main problem right now I see is error "Err: listen tcp 10.0.0.25:8301: bind: address already in use", which means the consul_agent is not started correctly, and I also see it's not correct via "sudo monit summary"

```
root@fb3d94b6-0077-4358-9a28-69b163b9d970:~# sudo monit summary
The Monit daemon 5.2.5 uptime: 11m

Process 'consul_agent'              not monitored
Process 'metron_agent'              running
Process 'consul_template'           not monitored
File 'haproxy_config'               accessible
Process 'haproxy'                   running
System 'system_localhost'           running
```
But I do see they are running
```
root@81a1c783-da5d-4d5d-a419-c2c44345e285:/var/vcap/sys/log/consul_agent# ps axu | grep consul
root      4171  0.0  0.0  18124  1696 ?        S<   10:50   0:00 /bin/bash -exu /var/vcap/jobs/consul_agent/bin/agent_ctl start
root      4172  0.0  0.0  18124  1696 ?        S<   10:50   0:00 /bin/bash -exu /var/vcap/jobs/consul_agent/bin/agent_ctl start
root      4173  0.0  0.0   4352  1404 ?        S<   10:50   0:00 tee -a /var/vcap/sys/log/consul_agent/consul_agent.stdout.log
root      4174  0.0  0.0   4344  1488 ?        S<   10:50   0:00 logger -p user.info -t vcap.consul-agent
root      4175  0.0  0.0   4352  1400 ?        S<   10:50   0:00 tee -a /var/vcap/sys/log/consul_agent/consul_agent.stderr.log
root      4176  0.0  0.0   4344  1524 ?        S<   10:50   0:00 logger -p user.error -t vcap.consul-agent
vcap      4184  0.2  0.4 156040 18340 ?        S<l  10:50   0:47 /var/vcap/packages/consul/bin/consul agent -config-dir=/var/vcap/jobs/consul_agent/config -recursor=10.0.0.2
root     24312  0.0  0.0  10472  2176 pts/0    S+   17:15   0:00 grep --color=auto consul
```

I can see the 8301 port is occupied by consul actually.
```
root@fb3d94b6-0077-4358-9a28-69b163b9d970:~# netstat -anp
udp        0      0 10.0.0.25:8301          0.0.0.0:*                           4195/consul
```

The versions are:
```
cf/230 
diego/0.1450.0
etcd/27
garden-linux/0.330.0
bosh-aws-xen-hvm-ubuntu-trusty-go_agent/3202
```

Below are the constructed deployment manifest and logs for ha_proxy job, can someone had one look on it to see why the consul is out of control?

https://github.com/cloudfoundry-incubator/diego-release/files/177732/minimal-vms.txt
https://github.com/cloudfoundry-incubator/diego-release/files/177737/ha_proxy_z1.0.2016-03-17-19-05-08.zip

**Comment by StanleyShen** [comment]
From monit log, I can see things like:
```
------------ STARTING agent_ctl at Thu Mar 17 10:50:58 UTC 2016 --------------
------------ STARTING agent_ctl at Thu Mar 17 10:52:03 UTC 2016 --------------
------------ STARTING agent_ctl at Thu Mar 17 10:53:14 UTC 2016 --------------
Removing stale pidfile...
------------ STARTING agent_ctl at Thu Mar 17 10:54:25 UTC 2016 --------------
Removing stale pidfile...
------------ STARTING agent_ctl at Thu Mar 17 10:55:37 UTC 2016 --------------
Removing stale pidfile...
------------ STARTING agent_ctl at Thu Mar 17 10:56:49 UTC 2016 --------------
Removing stale pidfile...
------------ STARTING agent_ctl at Thu Mar 17 10:58:00 UTC 2016 --------------
Removing stale pidfile...
------------ STARTING agent_ctl at Thu Mar 17 10:59:11 UTC 2016 --------------
Removing stale pidfile...
------------ STARTING agent_ctl at Thu Mar 17 11:00:22 UTC 2016 --------------
Removing stale pidfile...
------------ STARTING agent_ctl at Thu Mar 17 11:01:33 UTC 2016 --------------
Removing stale pidfile...
------------ STARTING agent_ctl at Thu Mar 17 11:02:45 UTC 2016 --------------
Removing stale pidfile...
------------ STARTING agent_ctl at Thu Mar 17 11:03:57 UTC 2016 --------------
Removing stale pidfile...
```

**Comment by Amit-PivotalLabs** [comment]
This issue was fixed in CF v231.  You can upgrade, or if you don't want to I can guide you to manually recover from this scenario.

**Comment by StanleyShen** [comment]
I tried to kill consul_agent process for failed VMs and did "monit restart consul_agent" 
And I can see some VMs are back.

Is the guide same with what I mentioned above?
If not, please show me the detail guide on it.

I would like to upgrade to v231 later.

**Comment by StanleyShen** [comment]
After these manual works, I still have some issues in my "services_z1/0".
```
Process 'consul_agent'              running
Process 'metron_agent'              running
Process 'uaa'                       running
Process 'cloud_controller_worker_1' Execution failed
File 'nfs_mounter'                  accessible
Process 'route_registrar'           running
System 'system_localhost'           running
```

For cloud_controller_worker_ctl the error shows
```
root@9b5940f0-8c78-4eb2-8883-f6fc631492a6:/var/vcap/sys/log# cat cloud_controller_worker_ctl.err.log
[2016-03-18 09:38:52+0000] ------------ STARTING cloud_controller_worker_ctl at Fri Mar 18 09:38:52 UTC 2016 --------------
[2016-03-18 09:39:32+0000] ------------ STARTING cloud_controller_worker_ctl at Fri Mar 18 09:39:32 UTC 2016 --------------
[2016-03-18 09:40:12+0000] ------------ STARTING cloud_controller_worker_ctl at Fri Mar 18 09:40:12 UTC 2016 --------------
[2016-03-18 09:41:02+0000] ------------ STARTING cloud_controller_worker_ctl at Fri Mar 18 09:41:02 UTC 2016 --------------
[2016-03-18 09:41:32+0000] chown: changing ownership of ‘/var/vcap/nfs/shared’: Operation not permitted
[2016-03-18 09:41:32+0000] chown: changing ownership of ‘/var/vcap/nfs/shared’: Operation not permitted
[2016-03-18 09:41:33+0000] chown: changing ownership of ‘/var/vcap/nfs/shared’: Operation not permitted
```

```
root@9b5940f0-8c78-4eb2-8883-f6fc631492a6:/var/vcap/sys/log# ps axu |  grep cloud_controller
root     11479  0.0  0.0  19592  1552 ?        S<   09:41   0:00 /bin/bash /var/vcap/jobs/cloud_controller_worker/bin/cloud_controller_worker_ctl start 1
root     11480  0.0  0.0  19592  1552 ?        S<   09:41   0:00 /bin/bash /var/vcap/jobs/cloud_controller_worker/bin/cloud_controller_worker_ctl start 1
root     11490  0.0  0.0  19600  1816 ?        S<   09:41   0:00 /bin/bash /var/vcap/jobs/cloud_controller_worker/bin/cloud_controller_worker_ctl start 1
root     11492  0.0  0.0  19600  1816 ?        S<   09:41   0:00 /bin/bash /var/vcap/jobs/cloud_controller_worker/bin/cloud_controller_worker_ctl start 1
root     11503  0.0  0.0   5916  1940 ?        S<   09:41   0:00 logger -p user.error -t vcap.cloud_controller_worker_ctl.stderr
root     11505  0.0  0.0   5916  1900 ?        S<   09:41   0:00 logger -p user.info -t vcap.cloud_controller_worker_ctl.stdout
root     13770  0.0  0.0  10472  2236 pts/0    S+   09:58   0:00 grep --color=auto cloud_controller
```

Is there any known issue for this?

Regardless these errors, the instance is able to login and enable diego support.
I tried to push a simple nodejs APP to this instance, and I got same error mentioned in issue https://github.com/cloudfoundry/cf-release/issues/932

```
Uploading stanley...
Uploading app files from: /Users/stanleyshen/workspace/stanley/hello
Uploading 885, 2 files
Done uploading
OK

Starting app stanley in org test / space test as admin...
FAILED
Server error, status code: 404, error code: 250003, message: The stack could not be found: The requested app stack cflinuxfs2 is not available on this system.
```

**Comment by Amit-PivotalLabs** [comment]
Hey @StanleyShen 

I'm not intimately familiar with the `cloud_controller_worker`.  You may wish to open an issue on the [Cloud Controller repo](https://github.com/cloudfoundry/cloud_controller_ng/issues) or ask on the [CAPI Slack channel](https://cloudfoundry.slack.com/messages/capi).

/cc @utako @SocalNick

**Comment by SocalNick** [comment]
@StanleyShen have you had any luck with this issue? It looks like the error(s) are happening here:

https://github.com/cloudfoundry/cloud_controller_ng/blob/bf11ed99b03705a2dcc1cca4d57d8bc10cdeb7a1/bosh-templates/handle_local_blobstore.sh.erb#L4

You might want to `bosh ssh` onto the VM in question and check the permissions of `/var/vcap/nfs/shared`. As Amit mentioned, you might want to the latest CF which is now v233. Also worth noting, these custom deployments are difficult for us to debug. We have a lot of experience and CI proving the default deployment strategies work.

Please open an issue an issue in [Cloud Controller](https://github.com/cloudfoundry/cloud_controller_ng/issues) if you are still having this problem.
